### ISSUE TITLE
Connecting resources error in Rhizi-Rhizi

### ISSUE THREAD

**Issue by Garbash** [willzeng/WikiNets#102]
When I've tried to connect resource "Roy Robanenko" using a long description in the connection title( "Will help in raising funds in LA") it didn't work.
Only when I've changed connection title into "will_help" the connection was created.

**Comment by willzeng** [comment]
https://github.com/willzeng/WikiNets/commit/9fb469b59b358ed76ffd4029c0c169035175316a

This will be pushed to the rhizi-rhizi online version soon.
