### ISSUE TITLE
Make node name into hyperlink if node has URL

### ISSUE THREAD

**Issue by bhaugen** [willzeng/WikiNets#104]
Probably with target="_blank"

**Comment by Garbash** [comment]
+1

On Mon, Feb 17, 2014 at 7:34 PM, Bob Haugen notifications@github.comwrote:

> Probably with target="_blank"
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/willzeng/WikiNets/issues/104
> .

## 

Get some insight of what makes me tick:
My twitter https://twitter.com/#!/garbash
Rhizi.net mailing list https://groups.google.com/forum/#!forum/rhizinet

Dor Garbash
108 Rue du faubourg du temple, Paris 75011
+33-652919878

**Comment by willzeng** [comment]
I like this. Implemented in:

https://github.com/willzeng/WikiNets/commit/59bebe231d960f7e195333b65acb4ac9479fa65b
https://github.com/willzeng/WikiNets/commit/44ce863c648fb45e628ce4f3f2e951c8f2230c32

**Comment by bhaugen** [comment]
Thanks for the quick response.

Deployed on http://wikinets-edge.herokuapp.com/? Just tried, did not work.

**Comment by willzeng** [comment]
It is on the wikinets-demo.herokuapp.com right now.  Surprisingly the demo
was updated before the edge right now (we're moving away from using the
edge instance)

**Comment by bhaugen** [comment]
Thanks again, got it.

Wow, my little test nodes live on the other instance, too!
