### ISSUE TITLE
Editing links

### ISSUE THREAD

**Issue by Garbash** [willzeng/WikiNets#106]
When trying to edit a link, the edit menu appears but there isn't any button to save the edit.

**Comment by willzeng** [comment]
Interesting.  I haven't run into this issue.  Are you sure that this
happens when all the resources of the page have loaded?

**Comment by Garbash** [comment]
![screen shot 2014-02-18 at 9 18 19 am](https://f.cloud.github.com/assets/1841864/2192702/e9f8fe5c-986c-11e3-95c4-0145c5d6fb37.png)
This is what I get. What should I do to finalise the edit?

**Comment by CalvinFong** [comment]
Yeah that bug happens occasionally when the resources on the page aren't loaded. Just refresh the page for now. I'll see if a $(document).ready fixes it.
