### ISSUE TITLE
Bug - when trying to change node color get Cannot POST /

### ISSUE THREAD

**Issue by Garbash** [willzeng/WikiNets#110]

**Comment by willzeng** [comment]
Is this an error in the console?

**Comment by Garbash** [comment]
It redirects to a page with that text

On Wed, Feb 19, 2014 at 4:12 PM, Will Zeng notifications@github.com wrote:

> Is this an error in the console?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/willzeng/WikiNets/issues/110#issuecomment-35502112
> .

## 

Get some insight of what makes me tick:
My twitter https://twitter.com/#!/garbash
Rhizi.net mailing list https://groups.google.com/forum/#!forum/rhizinet

Dor Garbash
108 Rue du faubourg du temple, Paris 75011
+33-652919878
