### ISSUE TITLE
When creating a new node, it should be created in a place that makes sense

### ISSUE THREAD

**Issue by Garbash** [willzeng/WikiNets#119]
A couple of options that make sense to me:
-Next to the creation section(up-right corner)
-Next to the node I've created last(and up-right corner, if this is first one in session)

**Comment by Garbash** [comment]
I think it's important to consider that in the act of creating a node, I
was already in a certain context, looking at a certain cluster.
I think that after creating a node, the person using the system should
remain where he was before, but be see the newly created node.

On Thu, Feb 20, 2014 at 12:33 AM, zhangjiannan notifications@github.comwrote:

> The node will be directed by the force from other node anyway, unless you
> pin it.
> Good to implement feature to put focus on the newly created node (center
> it).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/willzeng/WikiNets/issues/119#issuecomment-35558287
> .

## 

Get some insight of what makes me tick:
My twitter https://twitter.com/#!/garbash
Rhizi.net mailing list https://groups.google.com/forum/#!forum/rhizinet

Dor Garbash
108 Rue du faubourg du temple, Paris 75011
+33-652919878

**Comment by zhangjiannan** [comment]
then one interesting possibility is to hold the node with your mouse and put the node where you want on the canvas.

**Comment by Garbash** [comment]
I like the idea, but on the other hand, you increase cognitive load by
making me decide where to drop the resource as well as potentially breaking
a flow if I'm inputting many resources in succession.
some other ideas:
- put in a sandbox at some :fixed position in the corner of the screen.
- pin the newly created resource next to the input box.

On Thu, Feb 20, 2014 at 5:09 PM, zhangjiannan notifications@github.comwrote:

> then one interesting possibility is to hold the node with your mouse and
> put the node where you want on the canvas.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/willzeng/WikiNets/issues/119#issuecomment-35630433
> .

## 

Get some insight of what makes me tick:
My twitter https://twitter.com/#!/garbash
Rhizi.net mailing list https://groups.google.com/forum/#!forum/rhizinet

Dor Garbash
108 Rue du faubourg du temple, Paris 75011
+33-652919878

**Comment by willzeng** [comment]
This is actually easy enough to implement if anyone wants to grab it.  Perhaps @zhangjiannan?

All you need to do is set a newly created node to have the following properties:

```
node.fixed = true
node.x = x_initial
node.y = y_initial
```

where `x_initial` and `y_initial` are wherever you want it to start and stay fixed. When the users drags it, then it will later become unfixed.

These should just be properties in the `GraphView` though, so there should be a new `putNode` method along the lines of `putNewNode` that automatically adds these objects.

**Comment by willzeng** [comment]
So I did the simple thing and have newly created nodes appear fixed and selected in the center.  

When you click them again they become unfixed and will float wherever.

https://github.com/willzeng/WikiNets/commit/d2f4e86299e4138a244ca5d30b10a0832b0a0a0f

I took a look at having it appear next to the creation box, but this is still a little confusing and hard to find, while the center is obvious and doesn't seem to get in the way of much.  Thoughts? @Garbash

**Comment by Garbash** [comment]
Just tried it. The issue I have with it, is that if I'm happened to be
zoomed in on some cluster, or just away from the center, I don't get the
feedback of seeing the node appear. If there's a quick fix to make sure it
appears in "my" view it would be ideal.

On Thu, Feb 20, 2014 at 9:48 PM, Will Zeng notifications@github.com wrote:

> So I did the simple thing and have newly created nodes appear fixed and
> selected in the center.
> 
> When you click them again they become unfixed and will float wherever.
> 
> d2f4e86https://github.com/willzeng/WikiNets/commit/d2f4e86299e4138a244ca5d30b10a0832b0a0a0f
> 
> I took a look at having it appear next to the creation box, but this is
> still a little confusing and hard to find, while the center is obvious and
> doesn't seem to get in the way of much. Thoughts? @Garbashhttps://github.com/Garbash
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/willzeng/WikiNets/issues/119#issuecomment-35661343
> .

## 

Get some insight of what makes me tick:
My twitter https://twitter.com/#!/garbash
Rhizi.net mailing list https://groups.google.com/forum/#!forum/rhizinet

Dor Garbash
108 Rue du faubourg du temple, Paris 75011
+33-652919878

**Comment by willzeng** [comment]
Ah right, I forgot about zooming and translating.  This fix can be done
easily.  I'll put it on the list.

**Comment by zhangjiannan** [comment]
OK, just curious, without keep track of the drag/zoom position change, is there a simple way to get the current screen center position in canvas?

**Comment by willzeng** [comment]
Check out branch centeringfix

**Comment by willzeng** [comment]
Got it working:
https://github.com/willzeng/WikiNets/commit/13030ad5ac581addfa3e6d041c24db829429b831
