### ISSUE TITLE
Impossible to delete nodes in rhizi-sandbox 

### ISSUE THREAD

**Issue by Garbash** [willzeng/WikiNets#120]
even after waiting for map to completely load.
Clicking on edit button, doesn't reveal "delete" button

**Comment by zhangjiannan** [comment]
It works fine for me.

**Comment by Garbash** [comment]
tried again, waited patiently for all resources to load, still didn't work.
![screen shot 2014-02-20 at 5 09 45 pm](https://f.cloud.github.com/assets/1841864/2219483/2907945c-9a41-11e3-8fa4-cc2079aa75d8.png)

Used chrome Version 32.0.1700.107

**Comment by willzeng** [comment]
Yep we're aware of this error.  The error occurs when jquery and the colorPicker don't fully load in the page.  I'm not sure what is causing them not to load, but they seem to do so randomly sometimes (way too often actually).

We'll need to figure out a more robust way to load these resources so this doesn't happen as often.

In the meantime, if you refresh the page enough, eventually it will work.

@CalvinFong might be able to take a look at the color picker side of things
