### ISSUE TITLE
Add a "Centre this node" button to the node details view

### ISSUE THREAD

**Issue by backens** [willzeng/WikiNets#126]
This would alleviate some of the issues with finding nodes in the graph.

**Comment by Garbash** [comment]
+1
I would even push this further, no need for a button, clicking anywhere in
the node details view, should center on the node.

On Fri, Feb 21, 2014 at 7:00 PM, backens notifications@github.com wrote:

> This would alleviate some of the issues with finding nodes in the graph.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/willzeng/WikiNets/issues/126
> .

## 

Get some insight of what makes me tick:
My twitter https://twitter.com/#!/garbash
Rhizi.net mailing list https://groups.google.com/forum/#!forum/rhizinet

Dor Garbash
108 Rue du faubourg du temple, Paris 75011
+33-652919878

**Comment by willzeng** [comment]
This has been implemented.
