### ISSUE TITLE
Warning if node you're editing has changed on server

### ISSUE THREAD

**Issue by willzeng** [willzeng/WikiNets#131]
This might happen if multiple people are editing the same node at the same time. Should be easy to do based on _Last_Edit_Date.

**Comment by backens** [comment]
Very basic implementation in 9aa1f809ef0e9c09bc8889fcd3528ed266f913ac -- could probably make this much more informative if we have the time.

**Comment by backens** [comment]
I'll close this for now and add a new issue (which won't be in this milestone) for the "more informative warning message" part.
