### ISSUE TITLE
Extend VisualSearch to links

### ISSUE THREAD

**Issue by willzeng** [willzeng/WikiNets#132]

**Comment by backens** [comment]
Can now use VisualSearch to find either links or nodes. In case of links, the start and end nodes of all links matching the search query are added to the graph (which automatically adds the links). It's not very fast though... maybe we could cache lists of node/link properties? That might be useful for other predictive-input stuff as well.

See branch visualsearch, 6e13d8c3e341e518d4bb28af686c08c3332a223e

**Comment by willzeng** [comment]
Looking good.  I made a few in-line comments.
- One easy way to cache is to already use what we have loaded client side,
  i.e. all the keys and values in the GraphModel.
- I also agree that it would be useful for other predictive inputs.

**Comment by backens** [comment]
The problem with using the stuff in the GraphModel is (a) I don't know how to extract it and (b) it doesn't reflect changes to the database made by other users in the meantime. (b) is going to be an issue with any sort of caching, we could possibly refresh the cache every so often to mitigate that. We could just add a query to /get_all_node_keys and /get_all_link_keys when first loading the page, but that would slow down the initial loading time...

Anyway, the cache would also be useful for #130 and possibly for #133, so we should really implement that.

**Comment by backens** [comment]
No cache yet, but basic functionality (including switching between SimpleSearch and VisualSearch) is available as of f2db6c2b385720dac4ecd7f6fb8487400f5719c6
