### ISSUE TITLE
Center on doubleclick

### ISSUE THREAD

**Issue by davidfurlong** [willzeng/WikiNets#135]

**Comment by willzeng** [comment]
Dblclick a node centers it:
https://github.com/willzeng/WikiNets/commit/131cc3af6440d4f5d0ba901b1a5a7ee86930ebca

Dblclick a link centers it:
https://github.com/willzeng/WikiNets/commit/6cc84a893a1ce622a6c044c32ee5ac4c12b29969

@tmad4000 At last!

**Comment by davidfurlong** [comment]
Good job will - jacob
