### ISSUE TITLE
url parsing problems

### ISSUE THREAD

**Issue by backens** [willzeng/WikiNets#136]
- [x] parsing of https-links doesn't always work correctly
- [x] there is something wrong with the hyper link being created for the "name" field of a link that has a "url" attribute -- see e.g. the link connecting test and test2 in wikinets-edge

**Comment by willzeng** [comment]
Fixed the second half of this with:
https://github.com/willzeng/WikiNets/commit/7783ba981369451811fd153b009a5583cd7359f8

Will need to add a better regular expression to fix the first half.

**Comment by willzeng** [comment]
Done: https://github.com/willzeng/WikiNets/commit/3c57f34e56177b428940307bb6df71669903dfc0
