### ISSUE TITLE
Refactor to move create/edit/destroy actions into one module

### ISSUE THREAD

**Issue by vpontis** [willzeng/WikiNets#147]
One module should be responsible for creating, editing, and deleting nodes. It will act as an API for managing the data. Once we have abstracted this we can call these functions to modify our data.

**Comment by willzeng** [comment]
How should this be different than the `Neo4jDataController.coffee` plugin?

**Comment by vpontis** [comment]
Hmm yea, I forgot about this. I need to play with it more. Check out my pull requests when you get a chance.
