### ISSUE TITLE
Pull Request All Changes

### ISSUE THREAD

**Issue by vpontis** [willzeng/WikiNets#153]
We **really really really** need to do this. Before pushing code we need to get other people to look at it and approve it unless it is a really minor change. If we don't do this we will get a lot of problems and this should help fix a lot of problems that we currently have in our code. 

An example problem, in wikinets-default.less we currently have:

```
padding:4px;
padding-top:7px;
padding-bottom:1px;
padding-left:7px;
```

Which makes less than zero sense.

**Comment by vpontis** [comment]
@davidfurlong @willzeng @tmad4000 @backens

**Comment by willzeng** [comment]
+1 @zhangjiannan
