### ISSUE TITLE
Make Arrows Selectable

### ISSUE THREAD

**Issue by willzeng** [willzeng/WikiNets#16]
Should then show up in some sort of Node Details box

**Comment by backens** [comment]
Should this become a part of NodeSelection and NodeEdit, or a stand-alone plugin?

**Comment by willzeng** [comment]
Perhaps the best way to go would be to make an ArrowSelection and ArrowEdit plugin with functionality analogous to their Node versions.

This is a good idea as it separates the selection functionality from the way we actually choose to view/edit the arrows.

Ideally we might want an ArrowAndNodeEdit plugin, but that won't be hard to make as phase two.

Does this make sense?

**Comment by backens** [comment]
basic selection functionality implemented in fd00be045dc8953c1ed7372b35ff91213e7fcac8

Might want to change the highlighting colour as it's not very easily distinguishable from the standard colour at the moment.

Will add Editing functionality to this soon.

**Comment by backens** [comment]
Editing functionally implemented in de9906f492e980e270f1e5e993f5e462a476ec0f

**Comment by willzeng** [comment]
Hurray!
