### ISSUE TITLE
Make changes on the server propagate to the client

### ISSUE THREAD

**Issue by backens** [willzeng/WikiNets#162]
Currently there is a basic warning if a user tries to save a node that has been changed by someone else in the meantime. This warning should ideally contain information about what exactly has changed, as well as an option to merge the changes.

**Comment by vpontis** [comment]
Moreover. This ideally should be responsive! The node should change when changed on the server.

**Comment by willzeng** [comment]
muttering about websockets...  Should we just make a separate issue for
this general problem?

Perhaps it is not worth spending too much time on the current version if we
are going to switch to a better setup where database changes are pushed to
the client.

**Comment by vpontis** [comment]
Yea, I think that makes sense. It'll be interesting to see what Sashko has to say about Meteor and how that could possibly help some of our problems.
