### ISSUE TITLE
 fix the JavaScript loading race condition

### ISSUE THREAD

**Issue by tmad4000** [willzeng/WikiNets#164]
and the double loading of jquery
Probably using requirejs shim

**Comment by backens** [comment]
We're already using shim in `Celestrium.coffee`, but clearly the dependency lists in there aren't quite right yet. See also #163 for a list of some of the weird things in our library files.

**Comment by vpontis** [comment]
Do you have more information on this issue? What are you referring to?

**Comment by backens** [comment]
I've fiddled with shim a bit while upgrading VisualSearch -- see aba7abcb5083da006888af28b9df0d5960dd52b4 and previous commits on the visualsearch branch.

Would be nice to get some feedback as to which loading race issues persist, things seem to be working fine on my computer right now.

**Comment by vpontis** [comment]
I'm going to close this issue. If we find something specific we can reopen it.
