### ISSUE TITLE
Implement Starcraft-like edge scrolling

### ISSUE THREAD

**Issue by tmad4000** [willzeng/WikiNets#23]
In fullscreen mode, the map is in the bg of all, and your toolbar panels are just like a heads-up display.

You must move to edge of window entirely to scroll.

**Comment by willzeng** [comment]
Note that in https://github.com/willzeng/celestrium/pull/2 the edge scrolling only occurs at the edges of the #maingraph element.

If edge scrolling occurs, then it would be probably best to implement it in full screen mode only and when the cursor moves beyond the screen edge.
