### ISSUE TITLE
Polish Create Plugin

### ISSUE THREAD

**Issue by willzeng** [willzeng/WikiNets#27]

**Comment by willzeng** [comment]
Mostly implemented with this commit: https://github.com/willzeng/WikiNets/commit/ea9612d3c0267d15cb4228c82535c31ff841d7f1

@backens Still might want to have a think about hotkeys to speed up link and node creation.
- s to start selecting the source?
- t to start selecting the target?

**Comment by willzeng** [comment]
@backens Noticed a bug, that pressing the button to remove fields does not decrement the nodeInputNumber

**Comment by backens** [comment]
Why is that a bug? The nodeInputNumber doesn't need to be decreased, 
that's just a dummy counter to assign unique id's. If we did start 
decreasing it, we'd either have to rename some things, which would be a 
lot of hassle, or we'd get name space collisions.

**Comment by willzeng** [comment]
I wanted access to how many fields we currently displayed to check to see if I should auto-add a field on right-click.  You're right about `nodeInputNumber` though.  Do you think it would be better for me to add another seperate counter variable? Perhaps `nodeDisplayedFields`?

**Comment by backens** [comment]
Not sure why you want to auto-add a field on right-click. Is this to do 
with the idea about right-clicking into empty space to create a node? We 
don't currently auto-add a field when node creation starts, though that 
could probably be done.

It seems like we shouldn't need a counter to keep track of how many 
displayed fields there are, you should be able to extract it from the 
DOM somehow. The fields do all have the same class, which is otherwise 
unique, right?

**Comment by willzeng** [comment]
Yeah, when you right-click it now opens up the Create Menu and autoadds a field with the property Name.  

I'll take a look at extracting it from the DOM.  Note also that there is something a bit weird that is keeping me from focusing on the value field that I autoadd.  Perhaps you could take a look, I'll drop you a line comment in the relevant commit.

**Comment by willzeng** [comment]
Fixed here: https://github.com/willzeng/WikiNets/commit/c49f2350c0cebe55ddab3da7322e5aa55efe7021

using `$('.NodeCreateDiv').length`

This plugin seems fairly polished to me (at least as far as duplicating enough functionality to merge into master)
Should we close the issue?

**Comment by backens** [comment]
Yes, I guess the create plugin is fine now. Though the right click thing 
doesn't work for me -- where do I need to click? I only ever get the 
browser's right-click menu.

**Comment by willzeng** [comment]
For me it works when you click on the graph. Here's a place to check it
online:

http://wikinets-edge.herokuapp.com/test

EDIT: Whoops, I hadn't realized that I needed to update the submodule.  It should work now.

**Comment by willzeng** [comment]
Re: autofill. It makes the most sense to autofill with the `name` property, but right now I see that this is a reserved property.  Does this need to be the case?

**Comment by backens** [comment]
The online version doesn't load properly for me, I just get the WikiNets 
header and then "Uncaught TypeError: Expecting a function in instanceof 
check, but got #<HTMLDivElement>" (this is in Chromium).

In the offline version, right-click brings up the browser menu. 
Left-clicking to dismiss that menu makes the graph element I've 
right-clicked on (a node or the entire canvas) stick to my cursor and 
move with it until I left click again. Not sure what's going on there.

I'll be travelling from early tomorrow and visiting relatives, so I'm 
not sure whether I'm going to get a lot of internet time for the next 
few days. Will let you know when I'm back somewhere with reasonable 
internet, probably on Tuesday.

**Comment by backens** [comment]
Not sure why I put name as a reserved property. Maybe I was thinking of 
"text" instead, since that seems to be used internally by the 
visualisation and just got them confused.

I'm a bit dubious about auto-filling a property with "name" because 
there are plenty of things that don't have names but titles or something 
else instead, and I'd rather avoid trying to squeeze them all into one 
schema.

**Comment by willzeng** [comment]
Weird I wonder what's going on with the online one.  I haven't gotten that error yet.

I realized about an hour ago that in the offline version the submodule wasn't updated so this was causing it to do nothing on the click. Hopefully after this commit https://github.com/willzeng/WikiNets/commit/afdc0d1e9599a5539320a2f29e1cedabff1e1340 things work for you offline.

Enjoy the travelling.  I switched the reserved property to 'text' since that matches with the one hardcoded into GraphView: https://github.com/willzeng/WikiNets/commit/d7a10411386c4a6306e2304bd26b2608166fb33f

Re: autofilling, I'm just using a placeholder to suggest what one could put to have it show up on the node. It doesn't hardcode any schema other than lightly suggest that you may want your node to have a name. A title instead would work fine, we'll just need to add a section to GraphModel that looks for either a name or a title (or whatever else) to fill in the hardcoded text attribute.

Btw NodeEdit looks great so far.

**Comment by backens** [comment]
Ah, I've updated the celestrium submodule, and the right-click thing is 
now working on the local version.
