### ISSUE TITLE
NodeEdit plugin doesn't show correct text for nodes with title instead of name

### ISSUE THREAD

**Issue by backens** [willzeng/WikiNets#36]
It should show the same text as the GraphView, just as for nodes with a name, but instead just shows "undefined".

The problem is most likely with the makeDisplayable function in the WikiNetsDataProvider, which is independent of the GraphView text finding function.

Might be related to the Settings plugin.

**Comment by willzeng** [comment]
https://github.com/willzeng/WikiNets/commit/f936cdbd3340550eaf4ef6db9d56447a00007424
