### ISSUE TITLE
when edge label is blank, it doesn't add

### ISSUE THREAD

**Issue by tmad4000** [willzeng/WikiNets#41]
This applied to plugin TopBarCreate

**Comment by willzeng** [comment]
Fixed by setting TopBarCreate Plugin to have default type of "link" in 6b78ddd14439bb9a16f0f84eca269612cd396546

**Comment by backens** [comment]
Is this really something we want to do though? I thought we wanted to 
encourage people to create meaningful links, and forcing them to add a 
meaningful label would be one way to accomplish that.
