### ISSUE TITLE
should description info of center node also be in explore tab?

### ISSUE THREAD

**Issue by tmad4000** [willzeng/WikiNets#47]

**Comment by willzeng** [comment]
I'm not sure what this means. If you mean that we should add tabs somewhere, etc. then we're leaving these sort of questions until we have some good feel of how we want the interface to look.

**Comment by tmad4000** [comment]
Simply, like in wikinets-jisc, I want to see if the node that is centered
in the explore tab to have it's description shown there

**Comment by willzeng** [comment]
So you mean to include the description of the center node within the
MiniMap plugin?

**Comment by tmad4000** [comment]
Yes!

On Mon, Jan 20, 2014 at 11:40 AM, Will Zeng notifications@github.comwrote:

> So you mean to include the description of the center node within the
> MiniMap plugin?
> 
> On Sun, Jan 19, 2014 at 1:49 PM, tmad4000 notifications@github.com
> wrote:
> 
> > Simply, like in wikinets-jisc, I want to see if the node that is
> > centered
> > in the explore tab to have it's description shown there
> > On Jan 19, 2014 10:16 AM, "Will Zeng" notifications@github.com wrote:
> > 
> > > I'm not sure what this means. If you mean that we should add tabs
> > > somewhere, etc. then we're leaving these sort of questions until we
> > > have
> > > some good feel of how we want the interface to look.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/willzeng/WikiNets/issues/47#issuecomment-32704959>
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/willzeng/WikiNets/issues/47#issuecomment-32708634>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/willzeng/WikiNets/issues/47#issuecomment-32752711
> .

## 

Jacob
qoɔɐɾ
