### ISSUE TITLE
should clicking (not double clicking though) on a node center it like before?

### ISSUE THREAD

**Issue by tmad4000** [willzeng/WikiNets#48]
like wikinets-jisc.herokuapp.com

**Comment by willzeng** [comment]
This is presently implemented with SHIFT-Click

**Comment by willzeng** [comment]
There is a bug that doesn't make this transition ease properly.

**Comment by willzeng** [comment]
just a reminder that the current status of this is that the transition works, but for some reason it hasn't yet figured out how to center in the right place.

Do you think you could take a look at getting this to work @tmad4000

**Comment by tmad4000** [comment]
Yes! After Monday

On Sat, Feb 8, 2014 at 3:34 PM, Will Zeng notifications@github.com wrote:

> just a reminder that the current status of this is that the transition
> works, but for some reason it hasn't yet figured out how to center in the
> right place.
> 
> Do you think you could take a look at getting this to work @tmad4000https://github.com/tmad4000
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/willzeng/WikiNets/issues/48#issuecomment-34546809
> .

## 

Jacob
qoɔɐɾ
