### ISSUE TITLE
make graph view, list view tabs

### ISSUE THREAD

**Issue by tmad4000** [willzeng/WikiNets#49]
even if we have nothing to populate list view with yet, it'll get our heads in order

**Comment by willzeng** [comment]
This will be done when we have an interface wireframe mocked up.

Also, this is a duplicate of:
https://github.com/willzeng/WikiNets/issues/12

**Comment by willzeng** [comment]
I'm basically reopening this just to close it with the new commit.

**Comment by willzeng** [comment]
Closed with the first implementation at:
https://github.com/willzeng/WikiNets/commit/55beca8e4080b4cd491cb21bbeb53957f1b4b3dc

@tmad4000
