### ISSUE TITLE
Various NodeEdit plugin bugs

### ISSUE THREAD

**Issue by backens** [willzeng/WikiNets#54]
- [ ] When deleting a node, its information does not disappear from the NodeEdit menu
- [ ] After the edit process is finished (either by clicking "save" or "cancel"), the node is unselected in the graph view, but the information remains in the NodeEdit menu -- this may well be related to the above issue
- [ ] When clicking the "Edit node" button, the displayed title of any node changes to "undefined"

**Comment by willzeng** [comment]
I think I got these all fixed in 123a7c2c6b81961fbb64d81ee3cf31edc9f4ec92

@backens Did I miss any of the bugs?
