### ISSUE TITLE
 Make blue highlight dots smaller (white borderish)

### ISSUE THREAD

**Issue by davidfurlong** [willzeng/WikiNets#59]

**Comment by willzeng** [comment]
By highlight dots, do you mean the filling in of nodes when they are selected?

Clarifications? @davidfurlong

**Comment by davidfurlong** [comment]
Yes

**Comment by willzeng** [comment]
go for it!

**Comment by davidfurlong** [comment]
I have tried, its only possible by using a gradient and that didn't seem to work for me..

**Comment by CalvinFong** [comment]
Hey, I'm pretty sure I got gradient working but i can't seem to find where the color change occurs for selection in the code (i've just got all nodes with a gradient fill at the moment). Could someone inform me of the file/line?

**Comment by backens** [comment]
The colour change lives in wikinets-defaults.less -- I just spent ages 
hunting that down so I can implement something similar for links. 
Selecting a node adds the class "selected", and then the less file 
specifies the new fill colour.

**Comment by CalvinFong** [comment]
okay thanks :D
I've got it working but i'm having trouble committing at the moment. I'll leave committing until tomorrow so that i don't end up breaking everything.

**Comment by backens** [comment]
Ah, that might be because I just pushed a lot of stuff to the 
repository. Let me know if you're still having problems tomorrow and we 
can sort that out.

**Comment by willzeng** [comment]
sounds like a safe bet to me.  I'll be in by 10am to check stuff out.

**Comment by CalvinFong** [comment]
151c9d628d1583a052483f1897cf6c59fb4d984a
