### ISSUE TITLE
should Search let us add all nodes that have some property, independent of the value?

### ISSUE THREAD

**Issue by backens** [willzeng/WikiNets#66]

**Comment by willzeng** [comment]
This is a good idea.  I vote Yes.

**Comment by backens** [comment]
Right, I'll look into that then.

**Comment by backens** [comment]
implemented in b40031fa20387f37b6e2e0feace5c4651b349492

The drop-down menu for values now has an option "(any)", which should hopefully be self-explanatory enough.
