### ISSUE TITLE
Creation Rework

### ISSUE THREAD

**Issue by willzeng** [willzeng/WikiNets#71]
Need to rework the way to create Nodes and Links.

Should have option fields automatically, i.e.
- [x] Name
- [x] URL
- [x] Description
- [ ](the color selector) https://github.com/willzeng/WikiNets/issues/67

and then allow any key value pairing.

**Comment by backens** [comment]
Select nodes before adding link data
Make clearer during creation that links are directional (i.e. "select start and end node" or something)
