### ISSUE TITLE
VisualSearch Bug

### ISSUE THREAD

**Issue by willzeng** [willzeng/WikiNets#75]
I'm getting a bug in visual search whenever I try to add nodes to a blank workspace.  The error is on the server side with the following messages:

```
Searching nodes
Executing start n=node(*) where n.name = 'Barney' return n;
POST http://localhost:7474/db/data/cypher > {"query": "start n=node(*) where n.name = 'Barney' return n;"}
TyperError: Cannot read property 'length' of undefined
    at new neo4j.cypher.QueryResult (PATH TO THIS FILE)
etc.
```

is anyone else getting this error?
@CalvinFong @backens

**Comment by backens** [comment]
I'm not getting that error with the search query, in my case it's caused by the program trying to get the links for the single node. (It doesn't seem to break anything though -- the node still shows up -- which is why I've not reported it).

**Comment by willzeng** [comment]
This came from using an older version of Neo4j locally.  Should be fixed in newer versions.

Miriam added the requirement to the README
