### ISSUE TITLE
timestamps on nodes and links

### ISSUE THREAD

**Issue by backens** [willzeng/WikiNets#77]
Nodes and links should automatically be timestamped upon creation and upon editing.

**Comment by CalvinFong** [comment]
3e7b42da08fc47451e75f65a90433b586b2688b8
There is no time stamp for editing a link yet.
The time stamp properties are hidden and are "Creation_Date" and "Last_Edit_Date"

Time stamps are of form:
Wed Feb 05 2014 12:26:58 GMT+0000 (GMT)
