### ISSUE TITLE
Convert Wikiscript.js to Celestrium plugin architecture (branch wikiscript-refactor)

### ISSUE THREAD

**Issue by willzeng** [willzeng/WikiNets#9]
I'm not sure if this is the best way to go about things, but there is certainly quite a lot of rewriting that can be done to upgrade. 

This amounts to re-writing wikiscript.js as different celestrium plugins. This will be done on the wikiscript-refactor branch.

Here is a partial list of how we could separate wikiscript's functionality into four plugins that each access the DataController.coffee:
- [x] DataController.coffee should pass calls to the server to make changes to the database (should make this as agnostic as possible).  These should include:
  - Add/Edit/Delete Node
  - Add/Edit/Delete Arrow
  - This would mimic DataProvider in that one would provide their own specific extension to this class depending on the back end being used. (Initially it would be set up to work with a Neo4j database)

There should then be four interfaces (plugins) that make calls to the DataController.
- [x] Node/Arrow Creator (i.e. Create Menu)
  - This should access DataController and directly submit key-value pairs etc. It only adds nodes/arrows and does not edit or delete them.
- [x] Syntax Creator (i.e. Syntax)
  - Uses DataController and NodeSelection to replicate the functionality of wikinets' syntax create.
- [x] Edit Nodes
  - This is modeled after the NodeDetails plugin (which accesses NodeSelection), and adds the DataController.  It shows the node details and then has a button to press that makes all the fields editable as well includes a delete button.
  - At some point this should do the same thing to arrows when they are clicked.
- [x] Passive Minimap
  - [x] Still needs to be made NodeHash agnostic.
  - [ ] Active MiniMap, i.e. that selects on the main graph

**Comment by jdhenke** [comment]
@willzeng here's my thoughts.

## Celestrium as Whole

Celestrium can be thought of as two pieces:
- Celestrium.coffee - this defines this pseudo-singleton [plugin architecture](https://github.com/jdhenke/celestrium/blob/26d367dce3ec7e3f3ff58b2e91c5eadf3c02901b/doc/paper.md#plugin-architecture)
- Everything else - plugins adhering to this architecture that (often) depend on each other.

Hopefully the built in plugins do what is needed. If not, as in your case, you do not necessarily have to modify Celestrium - you can just create your own plugins to include, as it seems you have for your minimap and as everyone must for their DataProvider implementations, for example.

That being said, it might make more sense to modify Celestrium if the changes you introduce will not mesh with how current plugins work i.e. if you had to change things about the GraphModel or GraphView, which are pretty central.

## Specific Plugins

Here's my take on the specifics. Just recommendations based on my gut reactions, so take it with a grain of salt.

### DataController

I like that you are taking a DataProvider approach and creating an abstract interface one must fully implement to work. You seemed to indicate that it would initially work with Neo4j, but I think it might be confusing to have default functionality in this case. For instance, you'd have to hard code the endpoint URLs of your particular setup - not very general. I recommend creating a Neo4jExampleDataController plugin which extends DataController. This would act as your working plugin implementation as well as a great reference for others implementing DataController.

### Node/Arrow Creator

I feel like CRUD operations which affect the actual graph DB should be part of the exposed API for DataController.

### Edit Nodes

To clarify, I think _extend_ should mean _model your implementation after_.

Per jdhenke/celestrium#50, I think making links first class is a high priority next step for Celestrium in general.

### Minimap

This is a great feature I'd love to see in core celestrium.

**Comment by willzeng** [comment]
Completed here: https://github.com/willzeng/WikiNets/commit/237601b38368f197c9e628127ff6a4c340a7c9c2
